version: '3'
services:
  server:
    build: .
    command: npm start
    ports:
      - $API_PORT:8081
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
